import 'package:flutter/gestures.dart';
import 'package:flutter/services.dart';
import 'package:win32/win32.dart';

import '../key_mouse/mouse_button.dart';

// 定义键码到键名的映射
final Map<int, String> keyCodeToNameMap = {
  VIRTUAL_KEY.VK_OEM_3: '`',
  VIRTUAL_KEY.VK_OEM_8: '`',
  VIRTUAL_KEY.VK_BACK: 'backspace',
  VIRTUAL_KEY.VK_TAB: 'tab',
  VIRTUAL_KEY.VK_RETURN: 'enter',
  VIRTUAL_KEY.VK_ESCAPE: 'esc',
  VIRTUAL_KEY.VK_SPACE: 'space',
  VIRTUAL_KEY.VK_PRIOR: 'pageup',
  VIRTUAL_KEY.VK_NEXT: 'pagedown',
  VIRTUAL_KEY.VK_END: 'end',
  VIRTUAL_KEY.VK_HOME: 'home',
  VIRTUAL_KEY.VK_LEFT: 'left',
  VIRTUAL_KEY.VK_UP: 'up',
  VIRTUAL_KEY.VK_RIGHT: 'right',
  VIRTUAL_KEY.VK_DOWN: 'down',
  VIRTUAL_KEY.VK_DELETE: 'delete',
  VIRTUAL_KEY.VK_CAPITAL: 'capslock',
  VIRTUAL_KEY.VK_NUMLOCK: 'numlock',
  VIRTUAL_KEY.VK_SCROLL: 'scrolllock',
  VIRTUAL_KEY.VK_SNAPSHOT: 'printscreen',
  VIRTUAL_KEY.VK_INSERT: 'insert',
  VIRTUAL_KEY.VK_LSHIFT: 'shiftleft',
  VIRTUAL_KEY.VK_RSHIFT: 'shiftright',
  VIRTUAL_KEY.VK_LCONTROL: 'ctrlleft',
  VIRTUAL_KEY.VK_RCONTROL: 'ctrlright',
  VIRTUAL_KEY.VK_LMENU: 'altleft',
  VIRTUAL_KEY.VK_RMENU: 'altright',
  VIRTUAL_KEY.VK_LWIN: 'winleft',
  VIRTUAL_KEY.VK_RWIN: 'winright',
  VIRTUAL_KEY.VK_F1: 'f1',
  VIRTUAL_KEY.VK_F2: 'f2',
  VIRTUAL_KEY.VK_F3: 'f3',
  VIRTUAL_KEY.VK_F4: 'f4',
  VIRTUAL_KEY.VK_F5: 'f5',
  VIRTUAL_KEY.VK_F6: 'f6',
  VIRTUAL_KEY.VK_F7: 'f7',
  VIRTUAL_KEY.VK_F8: 'f8',
  VIRTUAL_KEY.VK_F9: 'f9',
  VIRTUAL_KEY.VK_F10: 'f10',
  VIRTUAL_KEY.VK_F11: 'f11',
  VIRTUAL_KEY.VK_F12: 'f12',
  VIRTUAL_KEY.VK_F13: 'f13',
  VIRTUAL_KEY.VK_F14: 'f14',
  VIRTUAL_KEY.VK_F15: 'f15',
  VIRTUAL_KEY.VK_F16: 'f16',
  VIRTUAL_KEY.VK_F17: 'f17',
  VIRTUAL_KEY.VK_F18: 'f18',
  VIRTUAL_KEY.VK_F19: 'f19',
  VIRTUAL_KEY.VK_F20: 'f20',
  VIRTUAL_KEY.VK_F21: 'f21',
  VIRTUAL_KEY.VK_F22: 'f22',
  VIRTUAL_KEY.VK_F23: 'f23',
  VIRTUAL_KEY.VK_F24: 'f24',
  VIRTUAL_KEY.VK_NUMPAD0: 'num0',
  VIRTUAL_KEY.VK_NUMPAD1: 'num1',
  VIRTUAL_KEY.VK_NUMPAD2: 'num2',
  VIRTUAL_KEY.VK_NUMPAD3: 'num3',
  VIRTUAL_KEY.VK_NUMPAD4: 'num4',
  VIRTUAL_KEY.VK_NUMPAD5: 'num5',
  VIRTUAL_KEY.VK_NUMPAD6: 'num6',
  VIRTUAL_KEY.VK_NUMPAD7: 'num7',
  VIRTUAL_KEY.VK_NUMPAD8: 'num8',
  VIRTUAL_KEY.VK_NUMPAD9: 'num9',
  VIRTUAL_KEY.VK_MULTIPLY: 'multiply',
  VIRTUAL_KEY.VK_ADD: 'add',
  VIRTUAL_KEY.VK_SEPARATOR: 'separator',
  VIRTUAL_KEY.VK_SUBTRACT: 'subtract',
  VIRTUAL_KEY.VK_DECIMAL: 'decimal',
  VIRTUAL_KEY.VK_DIVIDE: 'divide',
};

final logicalKeyMap = {
  LogicalKeyboardKey.altLeft: 'altleft',
  LogicalKeyboardKey.altRight: 'altright',
  LogicalKeyboardKey.arrowDown: 'down',
  LogicalKeyboardKey.arrowLeft: 'left',
  LogicalKeyboardKey.arrowRight: 'right',
  LogicalKeyboardKey.arrowUp: 'up',
  LogicalKeyboardKey.backspace: 'backspace',
  LogicalKeyboardKey.controlLeft: 'ctrlleft',
  LogicalKeyboardKey.controlRight: 'ctrlright',
  LogicalKeyboardKey.delete: 'delete',
  LogicalKeyboardKey.digit0: '0',
  LogicalKeyboardKey.digit1: '1',
  LogicalKeyboardKey.digit2: '2',
  LogicalKeyboardKey.digit3: '3',
  LogicalKeyboardKey.digit4: '4',
  LogicalKeyboardKey.digit5: '5',
  LogicalKeyboardKey.digit6: '6',
  LogicalKeyboardKey.digit7: '7',
  LogicalKeyboardKey.digit8: '8',
  LogicalKeyboardKey.digit9: '9',
  LogicalKeyboardKey.enter: 'enter',
  LogicalKeyboardKey.escape: 'esc',
  LogicalKeyboardKey.f1: 'f1',
  LogicalKeyboardKey.f2: 'f2',
  LogicalKeyboardKey.f3: 'f3',
  LogicalKeyboardKey.f4: 'f4',
  LogicalKeyboardKey.f5: 'f5',
  LogicalKeyboardKey.f6: 'f6',
  LogicalKeyboardKey.f7: 'f7',
  LogicalKeyboardKey.f8: 'f8',
  LogicalKeyboardKey.f9: 'f9',
  LogicalKeyboardKey.f10: 'f10',
  LogicalKeyboardKey.f11: 'f11',
  LogicalKeyboardKey.f12: 'f12',
  LogicalKeyboardKey.f13: 'f13',
  LogicalKeyboardKey.f14: 'f14',
  LogicalKeyboardKey.f15: 'f15',
  LogicalKeyboardKey.f16: 'f16',
  LogicalKeyboardKey.f17: 'f17',
  LogicalKeyboardKey.f18: 'f18',
  LogicalKeyboardKey.f19: 'f19',
  LogicalKeyboardKey.f20: 'f20',
  LogicalKeyboardKey.f21: 'f21',
  LogicalKeyboardKey.f22: 'f22',
  LogicalKeyboardKey.f23: 'f23',
  LogicalKeyboardKey.f24: 'f24',
  LogicalKeyboardKey.home: 'home',
  LogicalKeyboardKey.insert: 'insert',
  LogicalKeyboardKey.keyA: 'a',
  LogicalKeyboardKey.keyB: 'b',
  LogicalKeyboardKey.keyC: 'c',
  LogicalKeyboardKey.keyD: 'd',
  LogicalKeyboardKey.keyE: 'e',
  LogicalKeyboardKey.keyF: 'f',
  LogicalKeyboardKey.keyG: 'g',
  LogicalKeyboardKey.keyH: 'h',
  LogicalKeyboardKey.keyI: 'i',
  LogicalKeyboardKey.keyJ: 'j',
  LogicalKeyboardKey.keyK: 'k',
  LogicalKeyboardKey.keyL: 'l',
  LogicalKeyboardKey.keyM: 'm',
  LogicalKeyboardKey.keyN: 'n',
  LogicalKeyboardKey.keyO: 'o',
  LogicalKeyboardKey.keyP: 'p',
  LogicalKeyboardKey.keyQ: 'q',
  LogicalKeyboardKey.keyR: 'r',
  LogicalKeyboardKey.keyS: 's',
  LogicalKeyboardKey.keyT: 't',
  LogicalKeyboardKey.keyU: 'u',
  LogicalKeyboardKey.keyV: 'v',
  LogicalKeyboardKey.keyW: 'w',
  LogicalKeyboardKey.keyX: 'x',
  LogicalKeyboardKey.keyY: 'y',
  LogicalKeyboardKey.keyZ: 'z',
  LogicalKeyboardKey.numpad0: 'num0',
  LogicalKeyboardKey.numpad1: 'num1',
  LogicalKeyboardKey.numpad2: 'num2',
  LogicalKeyboardKey.numpad3: 'num3',
  LogicalKeyboardKey.numpad4: 'num4',
  LogicalKeyboardKey.numpad5: 'num5',
  LogicalKeyboardKey.numpad6: 'num6',
  LogicalKeyboardKey.numpad7: 'num7',
  LogicalKeyboardKey.numpad8: 'num8',
  LogicalKeyboardKey.numpad9: 'num9',
  LogicalKeyboardKey.numpadAdd: 'add',
  LogicalKeyboardKey.numpadDecimal: 'decimal',
  LogicalKeyboardKey.numpadDivide: 'divide',
  LogicalKeyboardKey.numpadEnter: 'enter',
  LogicalKeyboardKey.numpadMultiply: 'multiply',
  LogicalKeyboardKey.numpadSubtract: 'subtract',
  LogicalKeyboardKey.pause: 'pause',
  LogicalKeyboardKey.pageDown: 'pagedown',
  LogicalKeyboardKey.pageUp: 'pageup',
  LogicalKeyboardKey.printScreen: 'printscreen',
  LogicalKeyboardKey.scrollLock: 'scrolllock',
  LogicalKeyboardKey.shiftLeft: 'shiftleft',
  LogicalKeyboardKey.shiftRight: 'shiftright',
  LogicalKeyboardKey.space: 'space',
  LogicalKeyboardKey.tab: 'tab',
  LogicalKeyboardKey.capsLock: 'capslock',
  LogicalKeyboardKey.numLock: 'numlock',
};

final physicalKeyMap = {
  PhysicalKeyboardKey.f1: 'f1',
  PhysicalKeyboardKey.f2: 'f2',
  PhysicalKeyboardKey.f3: 'f3',
  PhysicalKeyboardKey.f4: 'f4',
  PhysicalKeyboardKey.f5: 'f5',
  PhysicalKeyboardKey.f6: 'f6',
  PhysicalKeyboardKey.f7: 'f7',
  PhysicalKeyboardKey.f8: 'f8',
  PhysicalKeyboardKey.f9: 'f9',
  PhysicalKeyboardKey.f10: 'f10',
  PhysicalKeyboardKey.f11: 'f11',
  PhysicalKeyboardKey.f12: 'f12',
  PhysicalKeyboardKey.tab: 'tab',
  PhysicalKeyboardKey.space: 'space',
  PhysicalKeyboardKey.backspace: 'backspace',
  PhysicalKeyboardKey.delete: 'delete',
  PhysicalKeyboardKey.capsLock: 'capslock',
  PhysicalKeyboardKey.shiftLeft: 'shiftleft',
  PhysicalKeyboardKey.shiftRight: 'shiftright',
  PhysicalKeyboardKey.controlLeft: 'ctrlleft',
  PhysicalKeyboardKey.controlRight: 'ctrlright',
  PhysicalKeyboardKey.altLeft: 'altleft',
  PhysicalKeyboardKey.altRight: 'altright',
  PhysicalKeyboardKey.arrowRight: 'right',
  PhysicalKeyboardKey.arrowLeft: 'left',
  PhysicalKeyboardKey.arrowUp: 'up',
  PhysicalKeyboardKey.arrowDown: 'down',
  PhysicalKeyboardKey.enter: 'enter',
  PhysicalKeyboardKey.escape: 'esc',
  PhysicalKeyboardKey.printScreen: 'printscreen',
  PhysicalKeyboardKey.scrollLock: 'scrolllock',
  PhysicalKeyboardKey.pause: 'pause',
  PhysicalKeyboardKey.insert: 'insert',
  PhysicalKeyboardKey.home: 'home',
  PhysicalKeyboardKey.end: 'end',
  PhysicalKeyboardKey.pageUp: 'pageup',
  PhysicalKeyboardKey.pageDown: 'pagedown',
  PhysicalKeyboardKey.numLock: 'numlock',
  PhysicalKeyboardKey.numpad0: 'num0',
  PhysicalKeyboardKey.numpad1: 'num1',
  PhysicalKeyboardKey.numpad2: 'num2',
  PhysicalKeyboardKey.numpad3: 'num3',
  PhysicalKeyboardKey.numpad4: 'num4',
  PhysicalKeyboardKey.numpad5: 'num5',
  PhysicalKeyboardKey.numpad6: 'num6',
  PhysicalKeyboardKey.numpad7: 'num7',
  PhysicalKeyboardKey.numpad8: 'num8',
  PhysicalKeyboardKey.numpad9: 'num9',
  PhysicalKeyboardKey.digit0: '0',
  PhysicalKeyboardKey.digit1: '1',
  PhysicalKeyboardKey.digit2: '2',
  PhysicalKeyboardKey.digit3: '3',
  PhysicalKeyboardKey.digit4: '4',
  PhysicalKeyboardKey.digit5: '5',
  PhysicalKeyboardKey.digit6: '6',
  PhysicalKeyboardKey.digit7: '7',
  PhysicalKeyboardKey.digit8: '8',
  PhysicalKeyboardKey.digit9: '9',
  PhysicalKeyboardKey.numpadAdd: 'add',
  PhysicalKeyboardKey.numpadSubtract: 'numpadSubtract',
  PhysicalKeyboardKey.numpadMultiply: 'numpadMultiply',
  PhysicalKeyboardKey.numpadDivide: 'numpadDivide',
  PhysicalKeyboardKey.numpadDecimal: 'numpadDecimal',
  PhysicalKeyboardKey.numpadEnter: 'numpadEnter',
  PhysicalKeyboardKey.numpadEqual: 'numpadEqual',
  PhysicalKeyboardKey.keyA: 'a',
  PhysicalKeyboardKey.keyB: 'b',
  PhysicalKeyboardKey.keyC: 'c',
  PhysicalKeyboardKey.keyD: 'd',
  PhysicalKeyboardKey.keyE: 'e',
  PhysicalKeyboardKey.keyF: 'f',
  PhysicalKeyboardKey.keyG: 'g',
  PhysicalKeyboardKey.keyH: 'h',
  PhysicalKeyboardKey.keyI: 'i',
  PhysicalKeyboardKey.keyJ: 'j',
  PhysicalKeyboardKey.keyK: 'k',
  PhysicalKeyboardKey.keyL: 'l',
  PhysicalKeyboardKey.keyM: 'm',
  PhysicalKeyboardKey.keyN: 'n',
  PhysicalKeyboardKey.keyO: 'o',
  PhysicalKeyboardKey.keyP: 'p',
  PhysicalKeyboardKey.keyQ: 'q',
  PhysicalKeyboardKey.keyR: 'r',
  PhysicalKeyboardKey.keyS: 's',
  PhysicalKeyboardKey.keyT: 't',
  PhysicalKeyboardKey.keyU: 'u',
  PhysicalKeyboardKey.keyV: 'v',
  PhysicalKeyboardKey.keyW: 'w',
  PhysicalKeyboardKey.keyX: 'x',
  PhysicalKeyboardKey.keyY: 'y',
  PhysicalKeyboardKey.keyZ: 'z',
};

// 反转 physicalKeyMap 的键值对
final Map<String, PhysicalKeyboardKey> stringToPhysicalKeyMap = Map.fromEntries(
    physicalKeyMap.entries.map((entry) => MapEntry(entry.value, entry.key)));

final mouseEventToNameMap = {
  kBackMouseButton: xbutton1,
  kForwardMouseButton: xbutton2,
  kMiddleMouseButton: middleButton,
  kSecondaryMouseButton: rightButton,
};

String getKeyName(int vkCode) {
  // 先从 Map 中查找对应的键名
  if (keyCodeToNameMap.containsKey(vkCode)) {
    return keyCodeToNameMap[vkCode]!;
  }
  // 处理字母和数字（A-Z, 0-9）
  if (vkCode >= 0x30 && vkCode <= 0x39) {
    // 数字键 0-
    return String.fromCharCode(vkCode);
  } else if (vkCode >= 0x41 && vkCode <= 0x5A) {
    // 字母 A-Z
    return String.fromCharCode(vkCode).toLowerCase();
  } else if (vkCode >= 0x60 && vkCode <= 0x69) {
    // 小键盘数字
    return 'NumPad ${vkCode - 0x60}';
  }
  return '0x${vkCode.toRadixString(16).padLeft(2, '0')}';
}
